# Generated by Django 2.2.13 on 2020-07-01 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('', '')], max_length=20)),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('short_name', models.CharField(max_length=20, verbose_name='short Name')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_value', models.FloatField(verbose_name='open')),
                ('high_value', models.FloatField(verbose_name='high')),
                ('low_value', models.FloatField(verbose_name='low')),
                ('close_value', models.FloatField(verbose_name='close')),
                ('volume', models.IntegerField(verbose_name='volume')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='stock.Company')),
            ],
            options={
                'verbose_name': 'daily price',
                'verbose_name_plural': 'daily prices',
            },
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'ticker',
                'verbose_name_plural': 'tickers',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_grade', models.CharField(choices=[('buy', 'Buy'), ('neutral', 'Neutral'), ('strong_buy', 'Strong Buy'), ('sell', 'Sell'), ('strong_sell', 'Strong Sell'), ('positive', 'Positive'), ('everything_else', 'Everything Else')], default='everything_else', max_length=20, verbose_name='to grade')),
                ('scalar', models.FloatField(editable=False, verbose_name='scalar')),
                ('daily_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='stock.DailyPrice')),
            ],
            options={
                'verbose_name': 'recommendation',
                'verbose_name_plural': 'recommendations',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='ticker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.Ticker'),
        ),
    ]
