# Generated by Django 2.2.14 on 2020-07-02 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('ticker', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ticker')),
                ('short_name', models.CharField(max_length=255, verbose_name='short Name')),
                ('sector', models.CharField(choices=[('it', 'IT'), ('finance', 'Finance')], max_length=20, verbose_name='sector')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(verbose_name='created_at')),
                ('open_value', models.FloatField(verbose_name='open')),
                ('high_value', models.FloatField(verbose_name='high')),
                ('low_value', models.FloatField(verbose_name='low')),
                ('close_value', models.FloatField(verbose_name='close')),
                ('volume', models.IntegerField(verbose_name='volume')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='stock.Company')),
            ],
            options={
                'verbose_name': 'daily price',
                'verbose_name_plural': 'daily prices',
                'unique_together': {('created_at', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
                ('to_grade', models.CharField(max_length=20, verbose_name='to grade')),
                ('scalar', models.FloatField(verbose_name='scalar')),
                ('daily_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='stock.DailyPrice')),
            ],
            options={
                'verbose_name': 'recommendation',
                'verbose_name_plural': 'recommendations',
            },
        ),
    ]
