# Generated by Django 2.2.13 on 2020-07-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprice',
            name='created_at',
            field=models.DateField(default=None, verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(max_length=50, verbose_name='short Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ticker',
            field=models.CharField(max_length=20, verbose_name='Ticker'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='scalar',
            field=models.FloatField(verbose_name='scalar'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='to_grade',
            field=models.CharField(max_length=20, verbose_name='to grade'),
        ),
        migrations.DeleteModel(
            name='Ticker',
        ),
    ]
