# Generated by Django 2.2.14 on 2020-07-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200702_1652'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyprice',
            unique_together={('created_at', 'company')},
        ),
    ]
