# Generated by Django 2.2.13 on 2020-07-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200701_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(choices=[('it', 'IT'), ('finance', 'Finance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='created_at',
            field=models.DateField(unique=True, verbose_name='created_at'),
        ),
    ]
