# Generated by Django 2.2.13 on 2020-07-02 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20200701_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
