# Generated by Django 2.2.13 on 2020-07-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_recommendation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ticker',
            field=models.CharField(max_length=10, unique=True, verbose_name='Ticker'),
        ),
    ]
