# Generated by Django 2.2.13 on 2020-07-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20200702_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.AlterField(
            model_name='company',
            name='ticker',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Ticker'),
        ),
    ]
