# Generated by Django 2.2.13 on 2020-07-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20200702_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyprice',
            name='company',
        ),
    ]
