# Generated by Django 2.2.13 on 2020-07-02 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_remove_dailyprice_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprice',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='stock.Company'),
            preserve_default=False,
        ),
    ]
