# Generated by Django 2.2.13 on 2020-07-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_dailyprice_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyprice',
            unique_together={('created_at', 'company')},
        ),
    ]
