# Development environment
version: '3'
services:
  db:
    image: 'postgres:11-alpine'
    restart: always
    # TODO: this data should be on automatic generated file
    environment:
      - POSTGRES_DB=dystematic
      - POSTGRES_USER=dystematic-user
      - POSTGRES_PASSWORD=dystematic-pass
    volumes:
      - db_data:/var/lib/postgresql/data
  
  api:
    build: .
    working_dir: /workspace/src
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 8000:8000
    volumes:
      - ./:/workspace

volumes:
 db_data: